version: '3.7'

services:
  php-fpm:
    image: panakour/phpdock_php-fpm:7.3
    restart: always
    environment:
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256
      - PHP_POST_MAX_SIZE=10
      - PHP_UPLOAD_MAX_FILESIZE=3
      - PHP_OPCACHE_MEMORY_CONSUMPTION=256

  nginx:
    image: panakour/phpdock_nginx:1.16.0
    restart: always

  mysql:
    restart: always