version: '3.7'

networks:
  backnet:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}

services:
  php-fpm:
    build:
      context: ./php/
      target: app-dev
      args:
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_MEMCACHED=true
        - INSTALL_PHPREDIS=true
        - INSTALL_IMAGEMAGICK=true
        # To authenticate to private registry either use username / password, or Oauth key/secret / etc
        # Please add Composer Auth JSON Object
        - COMPOSER_AUTH="{}"
    environment:
      - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    expose:
      - "9000"
    networks:
      - backnet

  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=php-fpm
        - PHP_UPSTREAM_PORT=9000
    environment:
      - NGINX_SERVER_TOKENS=on
      - SELF_SIGNED_SSL=1
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ./logs/nginx/:/var/log/nginx
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    networks:
      - backnet
    depends_on:
      - php-fpm

  mysql:
    image: mysql/mysql-server:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password # for mysql 8
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_CNF_FILE}:/etc/mysql/my.cnf
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - backnet