version: '3.8'

services:
  php-fpm:
    build:
      context: .
      target: php-prod
      args:
        - PHP_VERSION=${PHP_VERSION}
        - PHP_EXTENSIONS=${PHP_EXTENSIONS}
        # To authenticate to private registry either use username / password, or Oauth key/secret / etc
        # Please add Composer Auth JSON Object
        - COMPOSER_AUTH=${COMPOSER_AUTH}
    restart: unless-stopped

  nginx:
    build:
      context: .
      target: nginx-prod
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    environment:
      - NGINX_SERVER_TOKENS=off
    ports:
      - "80:80"
      - "443:443"
    depends_on:
        php-fpm:
          condition: service_healthy
    restart: unless-stopped

  mariadb:
    image: mariadb:${DB_VERSION}
    environment:
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ${DB_CNF_FILE}:/etc/mysql/my.cnf
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ${DB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    restart: unless-stopped
