version: '3.7'

services:
  php-fpm:
    build:
      context: ./php-fpm/7.4
    image: panakour/phpdock_php-fpm:7.4

  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=php-fpm
        - PHP_UPSTREAM_PORT=9000
    image: panakour/phpdock_nginx:1.16.0