version: '3.7'

services:
  php-fpm:
    build:
      context: ./php-fpm/${PHP_VERSION}
      args:
        - INSTALL_XDEBUG=true
        - INSTALL_MEMCACHED=true
        - INSTALL_PHPREDIS=true
        - INSTALL_IMAGEMAGICK=true
        - INSTALL_DEV_TOOLS=true
    environment:
      - EXPOSE_PHP=true
      - PHP_IDE_CONFIG=serverName=myide
      - PHP_MAX_EXECUTION_TIME=3600
      - PHP_MEMORY_LIMIT=4096
      - PHP_POST_MAX_SIZE=500
      - PHP_UPLOAD_MAX_FILESIZE=200
      - PHP_OPCACHE_MEMORY_CONSUMPTION=1024

  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=php-fpm
        - PHP_UPSTREAM_PORT=9000
    volumes:
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    environment:
      - NGINX_SERVER_TOKENS=on
      - SELF_SIGNED_SSL=1

  mysql:
    ports:
      - "3306:3306"
